# Generated by Django 4.1.4 on 2022-12-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_new_phone_user_otp_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
