# Generated by Django 4.1.4 on 2022-12-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_color_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
