# Generated by Django 4.1.4 on 2022-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_product_weihgts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='backend.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weihgts',
            field=models.ManyToManyField(to='backend.massa'),
        ),
    ]
