# Generated by Django 4.1.4 on 2022-12-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_product_colors_alter_product_weihgts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paind',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gramm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
    ]
