# Generated by Django 4.1.4 on 2022-12-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_paind_order_paid_order_color_order_gramm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('vaiting', 'VAITING'), ('canceled', 'CANCELED'), ('confirmed', 'CONFIRMED')], default='VAITING', max_length=100, null=True),
        ),
    ]
