# Generated by Django 4.1.5 on 2023-01-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_order_gramm_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartobject',
            name='gramm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.massa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='gramm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.massa'),
        ),
    ]
