name: Production Django deploy IdealDentBot

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "."
        target: "/home/Bot/Ideal-Dent"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          /home/Bot/Ideal-Dent/env/bin/pip install -r /home/Bot/Ideal-Dent/requirements.txt
          systemctl restart idealdent.service
          systemctl restart idealdentbot.service
          sh /home/devops/ideal_dent.sh "${{ github.event.head_commit.message }}"